### ISSUE TITLE
episode not working

### ISSUE THREAD

**Issue by Brijeshbabariya3** [KapilYadav-dev/MxPlayer-RestApi#1]

**Comment by KapilYadav-dev** [comment]
Hey @Brijeshbabariya3  can you please elaborate this issue as the episode I'm trying is working...

**Comment by Brijeshbabariya3** [comment]
https://mx-player-rest-api.vercel.app/detail?type=episode&url=https://www.mxplayer.in/show/watch-hello-mini/season-1/be-ready-mini-online-66036acf9bc95107b4cbd9f9fb2735ff

**Comment by KapilYadav-dev** [comment]
Hey @Brijeshbabariya3  I just saw that there is something wrong with vercel as if we run this server locally then its doing its job perfectly but on hosted vercel server it can't...
So, it's not a code related issue, so I'm closing this issue.
